# Setting up containers with services
services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - adelaide-network
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongodb-data:/var/lib/mongodb
    networks:
      - adelaide-network
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - 27017

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    hostname: postgresql
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - adelaide-network
    environment:
      - POSTGRES_DB=adelaide_db
      - POSTGRES_PASSWORD=adelaide
      - POSTGRES_USER=adelaide
    ports:
      - 5433:5432

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - adelaide-network
    environment:
      - REDIS_PASSWORD=adelaide
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - 6379:6379

  nexus:
    restart: always
    image: sonatype/nexus3
    container_name: nexus
    hostname: nexus
    volumes:
      - nexus-data:/nexus-data
    networks:
      - adelaide-network
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083

volumes:
  postgres-data:
    external: false
  mongodb-data:
    external: false
  redis-data:
    external: false
  rabbitmq-data:
    external: false
  nexus-data:
    external: false

networks:
  adelaide-network:
    name: adelaide_network
    external: false