# FOR DEVELOPMENT AND TEST PURPOSE ONLY
version: "3"
services:
  app:
    build: .
    container_name: adelaide-api
    depends_on:
      - rabbitmq
      - postgres
      - mongodb
      - redis
    ports:
      - "8081:8081"

  rabbitmq:
    restart: always
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: 'mongo:latest'
    hostname: mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'

  postgres:
    restart: always
    image: 'postgres:latest'
    hostname: postgresql
    volumes:
      - /var/lib/postgres/data
    environment:
      - 'POSTGRES_DB=adelaide_db'
      - 'POSTGRES_PASSWORD=adelaide'
      - 'POSTGRES_USER=adelaide'
    ports:
      - '5433:5432'

  redis:
    restart: always
    image: 'redis:latest'
    hostname: redis
    volumes:
      - "/var/lib/redis"
    environment:
      - REDIS_PASSWORD=adelaide
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "6379:6379"
