# FOR DEVELOPMENT AND TEST PURPOSE ONLY
services:
  #  app:
  #    build: .
  #    container_name: adelaide-api
  #    depends_on:
  #      - rabbitmq
  #      - postgres
  #      - mongodb
  #      - redis
  #      - nexus
  #    ports:
  #      - 9001:9001

  rabbitmq:
    restart: always
    image: rabbitmq:management
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672

  mongodb:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - mongodb-data:/var/lib/mongodb
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - 27017

  postgres:
    restart: always
    image: postgres:latest
    hostname: postgresql
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=adelaide_db
      - POSTGRES_PASSWORD=adelaide
      - POSTGRES_USER=adelaide
    ports:
      - 5433:5432

  redis:
    restart: always
    image: redis:latest
    hostname: redis
    volumes:
      - redis-data:/var/lib/redis
    environment:
      - REDIS_PASSWORD=adelaide
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - 6379:6379

  nexus:
    restart: always
    image: sonatype/nexus3
    hostname: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083

volumes:
  postgres-data:
    external: false
  mongodb-data:
    external: false
  redis-data:
    external: false
  rabbitmq-data:
    external: false
  nexus-data:
    external: false