version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'

  postgres:
    image: 'postgres:latest'
    volumes:
      - /var/lib/postgres/data
    environment:
      - 'POSTGRES_DB=adelaide_db'
      - 'POSTGRES_PASSWORD=adelaide'
      - 'POSTGRES_USER=adelaide'
    ports:
      - '5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
