server:
  port: 8080

spring:
  application.name: adelaide

  datasource:
    url: jdbc:postgresql://localhost:5432/adelaide_db
    username: adelaide
    password: adelaide

  flyway:
    url: jdbc:postgresql://localhost:5432/adelaide_db
    user: adelaide
    password: adelaide

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://adelaide:adelaide@localhost/adelaide?authSource=adelaide
