server:
  port: 8081

spring:
  application.name: adelaide

  rabbitmq:
    host: localhost
    username: rmuser
    password: rmpassword
    port: 5672

  mvc:
    log-resolved-exception: false

  datasource:
    url: jdbc:postgresql://localhost:5432/adelaide_db
    username: adelaide
    password: adelaide

  flyway:
    url: jdbc:postgresql://localhost:5432/adelaide_db
    user: adelaide
    password: adelaide

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://adelaide:adelaide@localhost/adelaide?authSource=adelaide
    redis:
      host: localhost
      password: adelaide

rabbitmq-default-queue: "adelaideQueue"