server:
  port: 9001

spring:
  application.name: adelaide

  rabbitmq:
    host: localhost
    username: adelaide
    password: adelaide
    port: 5672

  mvc:
    log-resolved-exception: false

  datasource:
    url: jdbc:postgresql://localhost:5432/adelaide
    username: adelaide
    password: adelaide

  flyway:
    url: jdbc:postgresql://localhost:5432/adelaide
    user: adelaide
    password: adelaide

  jpa:
    hibernate:
      ddl-auto: none
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: localhost
      username: adelaide
      password: adelaide
      database: adelaide
    redis:
      host: localhost
      password: adelaide

rabbitmq-default-queue: "adelaideQueue"

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
