server:
  port: 8081

spring:
  application.name: adelaide

  rabbitmq:
    host: rabbitmq
    username: rmuser
    password: rmpassword
    port: 5672

  mvc:
    log-resolved-exception: false

  datasource:
    url: jdbc:postgresql://postgresql:5432/adelaide_db
    username: adelaide
    password: adelaide

  flyway:
    url: jdbc:postgresql://postgresql:5432/adelaide_db
    user: adelaide
    password: adelaide

  jpa:
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      uri: mongodb://adelaide:adelaide@mongodb/adelaide?authSource=adelaide
    redis:
      host: redis
      password: adelaide

rabbitmq-default-queue: "adelaideQueue"