server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/adelaide_cdn_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/adelaide_cdn_db
