apiVersion: v1
kind: Namespace
metadata:
  name: adelaide
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJob3N0Lm1pbmlrdWJlLmludGVybmFsOjkyMDEiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW4iLCJhdXRoIjoiWVdSdGFXNDZZV1J0YVc0PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: local-nexus
  namespace: adelaide
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adelaide-api
  name: adelaide-api
  namespace: adelaide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adelaide-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adelaide-api
    spec:
      containers:
        - image: host.minikube.internal:9201/repository/docker/adelaide_api:0.0.1
          name: adelaide-api
          resources: {}
      imagePullSecrets:
        - name: local-nexus
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adelaide-api
  name: adelaide-api
  namespace: adelaide
spec:
  ports:
    - name: 9001-9001
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: adelaide-api
  type: ClusterIP
status:
  loadBalancer: {}