server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/adelaide_db
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/adelaide_db

cdn:
  url: http://localhost:8081/images/